"use client";
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';import {getCandidates} from '@/lib/candidates';import {createSubmission,updateSubmission,checkDuplicate} from '@/lib/submissions';import type {Candidate,JobSubmission,JobSubmissionFormData,SubmissionStatus} from '@/types/database';import {Input} from '@/components/ui/input';import {Button} from '@/components/ui/button';
const fields=['company_name','job_title','job_url','portal_source','job_location','vendor_company','vendor_contact_name','vendor_contact_email','vendor_contact_phone','submitted_rate','client_pay_rate','interview_time','interview_mode','interview_meeting_link','notes'] as const;
const statuses:SubmissionStatus[]=['Draft','Applied','Vendor_Screening','Submitted_to_Client','Interview_Scheduled','Round_1','Round_2','Offer_Received','Rejected','No_Response'];
export function SubmissionForm({initialSubmission,initialCandidateId,initialJob,backUrl='/dashboard/submissions',onSuccess}:{initialSubmission?:JobSubmission|null;initialCandidateId?:string;initialJob?:Partial<JobSubmission>;backUrl?:string;onSuccess?:(s:JobSubmission)=>void}) {
 const router=useRouter();const [candidates,setCandidates]=useState<Candidate[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[duplicate,setDuplicate]=useState(false);
 const [data,setData]=useState<Record<string,unknown>>(()=>({...Object.fromEntries(fields.map(k=>[k,null])),candidate_id:initialCandidateId||'',status:'Draft',submission_date:new Date().toISOString().slice(0,10),duplicate_flag:false,...initialJob,...initialSubmission}));
 useEffect(()=>{void getCandidates().then(setCandidates).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let cancelled=false;const company=String(data.company_name||''),id=String(data.candidate_id||'');if(company&&id){const timer=setTimeout(()=>void checkDuplicate(id,company).then(d=>!cancelled&&setDuplicate(d)).catch(e=>!cancelled&&setError(e.message)),300);return()=>{cancelled=true;clearTimeout(timer);};}},[data.company_name,data.candidate_id]);
 async function save(){setBusy(true);setError('');try{const result=initialSubmission?await updateSubmission(initialSubmission.id,data as unknown as JobSubmissionFormData):await createSubmission(data as unknown as JobSubmissionFormData);if(result.error||!result.data)throw new Error(result.error||'Save failed');onSuccess?.(result.data);router.push(backUrl);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="p-6 max-w-5xl mx-auto space-y-5"><Link href={backUrl}>Back to submissions</Link><h1 className="text-2xl font-bold">{initialSubmission?'Edit submission':'Create submission draft'}</h1><p>Saving a draft does not submit an external application. Applied is a manual recruiting status; automatic capture evidence is managed separately.</p><form onSubmit={e=>{e.preventDefault();void save();}} className="space-y-4"><label>Candidate<select required className="block border rounded p-2" value={String(data.candidate_id||'')} onChange={e=>{setData({...data,candidate_id:e.target.value});setDuplicate(false);}}><option value="">Choose candidate</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><div className="grid md:grid-cols-2 gap-4">{fields.map(k=><label key={k} className="capitalize">{k.replaceAll('_',' ')}<Input type={k==='interview_time'?'datetime-local':'text'} required={k==='company_name'||k==='job_title'} value={typeof data[k]==='string'?String(data[k]):''} onChange={e=>{setData({...data,[k]:e.target.value||null});setDuplicate(false);}}/></label>)}<label>Recruiting status<select className="block border rounded p-2" value={String(data.status)} onChange={e=>setData({...data,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Record date<Input required type="date" value={String(data.submission_date)} onChange={e=>setData({...data,submission_date:e.target.value})}/></label></div>{duplicate&&<p className="text-amber-700">Another submission to this company exists in the last 30 days. Review it before adding another.</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}<Button type="submit" disabled={busy||!data.candidate_id}>{busy?'Saving...':'Save submission record'}</Button></form></main>;
}