import {z} from 'zod';
export const matchSchema=z.object({requirements:z.array(z.object({requirement:z.string().min(1).max(200),jobEvidence:z.string().min(1).max(2000),status:z.enum(['met','missing','unknown']),candidateField:z.string().nullable(),candidateEvidence:z.string().nullable()}).strict()).max(60),constraints:z.array(z.object({field:z.enum(['authorized_in_usa','need_sponsorship_now','need_sponsorship_future','open_to_relocation']),requiredValue:z.boolean(),jobEvidence:z.string().max(2000)}).strict()).max(10)}).strict();
const norm=(s:string)=>s.toLowerCase().replace(/\s+/g,' ').trim();
export function validateMatch(input:unknown,facts:Record<string,unknown>,description:string){const parsed=matchSchema.parse(input);const requirements=parsed.requirements.filter(r=>norm(description).includes(norm(r.jobEvidence))&&norm(r.jobEvidence).includes(norm(r.requirement))).map(r=>{
 const value=r.candidateField?facts[r.candidateField]:null;const evidence=r.candidateEvidence;const supported=evidence&&typeof value==='string'&&norm(value).includes(norm(evidence));
 // A cited candidate fact alone does not prove an unrelated requirement. Missing facts are unknown.
 const escape=(v:string)=>v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const term=escape(norm(r.requirement));const exact=new RegExp('(^|[^a-z0-9])'+term+'(?=$|[^a-z0-9])','i');const negative=typeof value==='string'&&new RegExp('\\b(?:no|not|without)\\b[^.;\\n]{0,50}'+term,'i').test(value);
 const met=supported&&exact.test(norm(evidence))&&!negative;return {...r,status:r.status==='met'&&met?'met':'unknown',candidateEvidence:met?evidence:null};
 });const constraints=parsed.constraints.filter(c=>norm(description).includes(norm(c.jobEvidence))).map(c=>{const fact=facts[c.field];const relevant=c.field==='open_to_relocation'?/relocat/i.test(c.jobEvidence):c.field==='authorized_in_usa'?/authoriz|eligible/i.test(c.jobEvidence):/sponsor/i.test(c.jobEvidence);const negative=/\b(?:no|not|without|do not)\b/i.test(c.jobEvidence);const expected=c.field.startsWith('need_sponsorship')?!negative:!negative;
 const known=relevant&&c.requiredValue===expected&&typeof fact==='boolean';return {...c,status:known?(fact===c.requiredValue?'met':'conflict'):'unknown'};});
 return {requirements,constraints,coverage:requirements.length?Math.round(100*requirements.filter(r=>r.status==='met').length/requirements.length):null};}
